#!/bin/sh
set -eu
cd "$(git rev-parse --show-toplevel)"
echo Installing Python apps >> /dev/stderr
python3 -m pip install --user --requirement requirements.txt
echo Installing Git hooks >> /dev/stderr
Documents/bin/install-git-hooks
echo Generating SSH config >> /dev/stderr
Documents/bin/gen-ssh-config
echo Loading dconf config >> /dev/stderr
Documents/bin/dconf-load
echo Configuring Git repo >> /dev/stderr
git config --local status.showUntrackedFiles no
echo Adding Cron job >> /dev/stderr
Documents/bin/cron-jobs
