---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
        exclude: >-
          myclirc|netrc|packet-cli|mycli-history|scwrc|gcloud\.json|\.envrc\.private|\.config/systemd/user
      - id: check-toml
      - id: check-toml
        files: Pipfile
      - id: trailing-whitespace
        exclude: \.aspell\.en\.pws

  - repo: https://git.shore.co.il/nimrod/yamltool.git
    rev: v0.1.2
    hooks:
      - id: yamltool

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint

  - repo: https://github.com/amperser/proselint/
    rev: 0.13.0
    hooks:
      - id: proselint
        types: [plain-text]
        exclude: LICENSE

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--filter-files", "--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: &excluded_pythonscripts pythonrc.py|rabbitmqadmin
        args:
          - |
            --line-length=79

  - repo: https://github.com/PyCQA/prospector
    rev: v1.8.4
    hooks:
      - id: prospector
        exclude: *excluded_pythonscripts
        args:
          - |-
            --max-line-length=79
          - |-
            --with-tool=pyroma
          - |-
            --with-tool=bandit
          - |-
            --without-tool=pep257
          - |-
            --doc-warnings
          - |-
            --test-warnings
          - |-
            --full-pep8
          - |-
            --strictness=high
          - |-
            --no-autodetect
        additional_dependencies:
          - bandit
          - pyroma

  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: *excluded_pythonscripts
        args:
          - |-
            --doctests
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: rabbitmqadmin|\.config/git/config|Pipfile\.lock|npmrc

  - repo: https://git.shore.co.il/nimrod/pre-commit-hooks.git
    rev: v0.3.0
    hooks:
      - id: shell-validate
        exclude: &excluded_shellscripts |-
          \.bash_completion\.d/(docker-machine\.bash|fabric-completion.bash|docker-compose)
      - id: shell-validate
        files: '\.envrc$'
        types: [text]

  - repo: https://github.com/shellcheck-py/shellcheck-py.git
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        exclude: *excluded_shellscripts
      - id: shellcheck
        files: '\.envrc$'
        types: [text]

  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.16
    hooks:
      - id: mdformat

  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.3
    hooks:
      - id: gitlab-ci-linter
        args:
          - "--server"
          - https://git.shore.co.il

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: \.local/share/applications/.*\.desktop
        args:
          - "-L"
          - "doas"
