---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
        exclude: >-
          myclirc|netrc|packet-cli|mycli-history|scwrc|gcloud\.json|\.envrc\.private|\.config/systemd/user
      - id: check-toml
      - id: check-toml
        files: Pipfile
      - id: trailing-whitespace
        exclude: \.aspell\.en\.pws

  - repo: https://git.shore.co.il/nimrod/yamltool.git
    rev: v0.1.2
    hooks:
      - id: yamltool

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/amperser/proselint/
    rev: 0.14.0
    hooks:
      - id: proselint
        types: [plain-text]
        exclude: LICENSE

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--filter-files", "--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: &excluded_pythonscripts pythonrc.py|rabbitmqadmin
        args:
          - |
            --line-length=79

  - repo: https://github.com/pylint-dev/pylint.git
    rev: v3.3.3
    hooks:
      - id: pylint
        exclude: *excluded_pythonscripts
        args: ["--disable", "line-too-long,broad-exception-raised"]

  - repo: https://github.com/DanielNoord/pydocstringformatter.git
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        exclude: *excluded_pythonscripts

  - repo: https://github.com/PyCQA/bandit.git
    rev: "1.8.0"
    hooks:
      - id: bandit
        exclude: *excluded_pythonscripts

  - repo: https://github.com/pycqa/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: *excluded_pythonscripts
        args:
          - |-
            --doctests
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: rabbitmqadmin|\.config/git/config|Pipfile\.lock|npmrc

  - repo: https://git.shore.co.il/nimrod/pre-commit-hooks.git
    rev: v0.5.2
    hooks:
      - id: shell-validate
        exclude: &excluded_shellscripts |-
          \.bash_completion\.d/(docker-machine\.bash|fabric-completion.bash|docker-compose)
      - id: shell-validate
        files: '\.envrc$'
        types: [text]

  - repo: https://github.com/shellcheck-py/shellcheck-py.git
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: *excluded_shellscripts
      - id: shellcheck
        files: '\.envrc$'
        types: [text]

  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.21
    hooks:
      - id: mdformat

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: \.local/share/applications/.*\.desktop
        args:
          - "-L"
          - "doas"
