-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: flake8
        files: \.pythonstartup|Documents/Shore/cleanup/vagrant-.*
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.5.4
    hooks:
    -   id: shell-lint
        files: &shellscripts 'bashrc|post-merge|profile|docker-|train-wifi|renew-certs|dma-clean|gen-ssh-config'
    -   id: shellcheck
        files: *shellscripts
