-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: flake8
        files: \.pythonstartup|Documents/Shore/cleanup/vagrant-.*
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.5.4
    hooks:
    -   id: shell-lint
        files: &shellscripts 'bashrc|post-merge|profile|docker-|wifi-login|renew-certs|dma-clean|gen-ssh-config|dconf-load|install-git-hooks|pocketchip-battery|update-voltage'
    -   id: shellcheck
        files: *shellscripts
