---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: flake8
        exclude: pythonrc.py
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.6.0
    hooks:
    -   id: shell-lint
        exclude: &excluded_shellscripts \.bash_completion\.d/(docker-machine\.bash|fabric-completion.bash|docker-compose)|\.travis/travis\.sh
    -   id: shellcheck
        exclude: *excluded_shellscripts
        include: .bashrc
