# vim:ff=unix ts=2 sw=2 ai expandtab
---
language: python
python: "3.8"
dist: bionic
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install pre_commit

script:
  - pre-commit run --all-files

notifications:
  on_failure: never
  email: false
