---
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      group: beta
      language: python
      python: 3.6
      install:
          - pip install pre_commit | cat
    - os: osx
      language: generic
      install:
          - brew install shellcheck
          - pip install pre_commit | cat
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

addons:
  apt:
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main universe multiverse'
    packages:
      - shellcheck

script:
  - pre-commit run --all-files
  - cd; $TRAVIS_BUILD_DIR/install
  - git bull

notifications:
  email: false
