#!/bin/sh
# shellcheck disable=SC2046
set -u
docker rm $(docker ps --quiet --filter=status=exited) 2>/dev/null
docker rm $(docker ps --quiet --filter=status=created) 2>/dev/null
docker rmi $(docker images --quiet --filter=dangling=true) 2>/dev/null
docker volume rm $(docker volume ls --quiet --filter=dangling=true) 2>/dev/null
