#!/bin/sh
docker rm $(docker ps --quiet --filter=status=exited) || true
docker rm $(docker ps --quiet --filter=status=created) || true
docker rmi $(docker images --quiet --filter=dangling=true) || true
docker volume rm $(docker volume ls --quiet --filter=dangling=true) || true
